### ISSUE TITLE
"Error: There are no enabled repos." with epel-7-x86_64 config on Fedora 26

### ISSUE THREAD

**Issue by subpop** [rpm-software-management/mock#101]
When running `mock` on Fedora 26 using the `epel-7-x86_64` config, it fails to create the mock root, failing with the following error:

```
$ mock -r epel-7-x86_64 --shell
INFO: mock.py version 1.4.2 starting (python version = 3.6.2)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled yum cache
Start: cleaning yum metadata
Finish: cleaning yum metadata
INFO: enabled HW Info plugin
Start: yum install
Error: There are no enabled repos.
ERROR: Command failed: 
 # /usr/bin/yum --installroot /var/lib/mock/epel-7-x86_64/root/ --releasever 7 install @buildsys-build
Error: There are no enabled repos.
```

Adding `config_opts['package_manager'] = 'dnf'` to the config (`/etc/mock/epel-7-x86_64.cfg`) appears to fix it and build the root.

**Comment by xsuchy** [comment]
This happened when you do not have yum installed.  Yum is weak dependency and you can run mock without it.
I admit that this error is cryptic, but unfortunatelly I see no way how to make it better and not break compatibily for EL people.

Anyway installing `yum` package will fix your issue.

**Comment by xsuchy** [comment]
I dived into this later as I wanted to make this error more user friendly. And I found that:

* when package yum is not installed then /usr/bin/yum in fact points to dnf.
* We had /etc/dnf.conf but it was empty so dnf thinked that there is no configuration.
* I fixed it by copying content of yum.conf to /etc/dnf/dnf.conf (which should be used rather than /etc/dnf.conf)

Commits:
* ef5e849 (HEAD -> devel, origin/devel, origin/HEAD) populate /etc/dnf/dnf.conf even when using yum PM
* ebb2e5c create /etc/dnf directory
* 4b3eabb correct path is /etc/dnf/dnf.conf instead of /etc/dnf.conf

One thing is worth noting. In this situation you will silently use DNF for chroot, which is supposed to use YUM. This can lead to slightly different depsolving.
For the other way round (using YUM for chroots which should use DNF) we produce warning, which can be disabled using:

```
# Flip this if you want to get rid of warning message on systems which does not support DNF                                                      
# Warning! Setting this to False will automatically use Yum on RHEL{6,7} platforms.
# config_opts['dnf_warning'] = True
```

I have been thinking whether we should produce similar warning in this situation (and probably use the same option).  Right now I'm inclined to solution to NOT produce such warning.

**Comment by subpop** [comment]
> I have been thinking whether we should produce similar warning in this situation (and probably use the same option). Right now I'm inclined to solution to NOT produce such warning.

If using `dnf` in "yum mode" is strictly better, then I would agree to not produce a warning; the user doesn't need to be told about a change that is believed to be for the better.

However, if there are known possible differences that could be caused by using `dnf` in a chroot environment that expects `yum`, we should warn the user about a potential, unexpected change in the environment.

When I fire up a mock `epel-6` chroot, my instinctive thought is that I'm using a "full and proper" `yum`, not `dnf` in "yum mode".
