### ISSUE TITLE
Installing mock into mock root breaks everything

### ISSUE THREAD

**Issue by contyk** [rpm-software-management/mock#110]
On `init`, `mock` attempts to add the `mockbuild` (GID 135) group to the mock root but it fails because the group's already been created with its `%pre` installation scriptlet.

**Comment by xsuchy** [comment]
For the record: The reproducer is to:
```
config_opts['chroot_setup_cmd'] = 'install @buildsys-build mock'
```
which will install mock in buildroot and consequent groupdel fail (silently) because group mockbuild does not exists, but groupadd fail too (with TB) because there is group mock with the same gid.

I guess that best approach will be to rename group mockbuild inside of chroot to group mock.

**Comment by contyk** [comment]
+1
