### ISSUE TITLE
Support setting up foreign architecture chroots (with DNF)

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/mock#120]
Since DNF 2.6.2, it has been possible to make foreign architecture chroots. That is, chroots that are for an architecture that _isn't_ explicitly compatible with the host system.

The basic procedure is documented [here](https://npmccallum.gitlab.io/post/cross-architecture-roots-with-dnf/) by @npmccallum and [here](https://wiki.mageia.org/en/Using_DNF#Setting_up_a_container_for_a_non-native_architecture) by me.

It would make it easier for people to test builds for architectures they don't have locally. It'd probably be best to have a switch (like `--foreign-arch`, similar to debootstrap).

**Comment by npmccallum** [comment]
@Conan-Kudo FYI, your instructions include unnecessary and possibly inadvisable steps. You should use the 'F' flag in binfmt_misc instead of copying anything into the chroot. The chroot should be completely unmodified.

**Comment by Conan-Kudo** [comment]
@npmccallum It doesn't work without it. That's still not fixed, per [RHBZ#1470397](https://bugzilla.redhat.com/show_bug.cgi?id=1470397)

**Comment by npmccallum** [comment]
@Conan-Kudo What currently works is using the 'F' flag pointing to the static binaries in the host. This is due to an unfortunate limitation in the 'F' flag kernel implementation. It would be better if the kernel supported dynamic binaries rather than just static ones. But the 'F' flag should still work with static binaries. There is no need to modify the guest.

**Comment by npmccallum** [comment]
Also, restarting the service is no longer necessary. This is fixed in Fedora (the service is restarted in %post).
