### ISSUE TITLE
RFE: Provide an explicit package_manager name for dnf 4

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#1271]
Currently, to use dnf 4, one would set:

```python
config_opts["package_manager"] = "dnf"
```

@befeleme said (in other words): It's not clear what this means, can we say "dnf 4" more explicitly?

I've checked the code in mock:

https://github.com/rpm-software-management/mock/blob/cec199ef78a089d0aeb76817840bc86120fcdf60/mock/py/mockbuild/package_manager.py#L28-L37

Apparently, we cannot.

Would you please add an alias (or similar) so we can do:

```python
config_opts["package_manager"] = "dnf4"
```

Or:

```python
config_opts["package_manager"] = "dnf-3"
```

Thanks.

**Comment by Conan-Kudo** [comment]
We can add `dnf4`, that's what we did in KIWI for this a while back.

**Comment by praiskup** [comment]
While working on pr #1335, I'm not confident this DNF => DNF4 rename in Mock is the natural thing to do.  What do others think?  CC @jan-kolarik from DNF.

DNF always was named just DNF before, only by "accident" the last version is 4.X (in 2018, there was [v3](https://github.com/rpm-software-management/dnf/commit/197901eeaa5619f00f2d11ef1c9e8d78dca98df0), too).

The DNF v5 is aliased as DNF5 (everyone uses this), but it has its own versioning scheme (now v5.2.X).  But nothing prevents the DNF5 upstream from raising the version to v6.X in the future.

Also, at some distant point in the future, we'd like to call DNF5 just DNF because nobody will care about DNF4.  Both here in mock, and also in general. :shrug:

**Comment by hroncok** [comment]
In my head it's called dnf 4. Whether or not that is what upstream dnf wants I don't know. Perhaps it should be "legacy dnf" or something else entirely, but we would need to ask the dnf folks.

**Comment by jan-kolarik** [comment]
Hi guys,

I haven't been around long enough to remember pre-dnf 4.x, but here are my thoughts.

I see **dnf** as simply a reference to the default package manager version (4 or 5) relevant to a system. With the packages now separated, referring to just **dnf** will cause confusion.

In this context, it's clearer to use the specific dnf version, as mock doesn't have a "dnf default".

Regarding versioning, as we agreed in the team, dnf 4.x will not have major version bumps anymore, and so will dnf5. That's why we moved to the 5.X.Y.Z versioning scheme.
