### ISSUE TITLE
Older versions of usermod fails when trying to change user id to the current id of the user

### ISSUE THREAD

**Issue by andersrein** [rpm-software-management/mock#135]
We've made mock configuration for some older Linux versions. These versions will fail whenever restoring a cached root because of the _fixup_build_user (buildroot.py).

This function tries to make sure that the mockbuild user has the correct uid. To ensure this it runs usermod -u %{uid} mockbuild. For older versions of usermod this command fails if the uid is allready %{uid} because the id is not "unique". I've manage to work around this by changing the mock python code to also use the -o flag when calling usermod.

**Comment by xsuchy** [comment]
> For older versions of usermod this command fails if the uid is allready %{uid} because the id is not "unique

I cannot parse this sentence :)

> We've made mock configuration for some older Linux versions.

Can you state which versions of which Linux? Or even better, post the configs?

**Comment by arevizrt** [comment]
Sorry. I'll reformat the sentence :)

The usermod command will fail if you use -u to change user id to the user id which it already is. For instance if I've run mock once before and the mock user has ID 1000, then the next time I run mock it will restore the root from cache and run usermod -u 1000 on the mock user. This command will fail because 1000 is already taken by the mock user. So the point is that these older versions of usermod is not smart enough to realize that: yes, it is taken, but it is taken by the user we are changing so there really isn't any problem.

I can post the configs, but I don't think it will help you as it points to RPM repositories on our internal servers. The repositories are created from the SUSE Enterprise 11 DVDs.

**Comment by Conan-Kudo** [comment]
@arevizrt That answers that question about why it wasn't working for me with SLE 11. :)

**Comment by cheese** [comment]
But this change breaks EL5.

**Comment by cheese** [comment]
It may be a good idea first to run without '--non-unique', if failed then run with '--non-unique'.

**Comment by xsuchy** [comment]
EL5 is sensitive to order of params. Fixed in commit 90c1361

**Comment by cheese** [comment]
Thanks!
