### ISSUE TITLE
EPEL 10 chroots

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#1421]
Please add CentOS Stream 10 + EPEL 10 chroot configs. There is no compose yet, just the Koji buildroot.

Thanks.

cc @carlwgeorge

**Comment by hroncok** [comment]
https://kojipkgs.fedoraproject.org/repos/epel10.0-build/latest/

**Comment by carlwgeorge** [comment]
I was planning on doing this after we had it published and mirrored, to avoid hitting the koji tag repo to hard.  If that's not a concern I can send a PR with the configs, and then another later to switch to the mirror metalinks.

**Comment by hroncok** [comment]
I already hit the Koji repo manually, making it available in the official mock-core-configs might expose a bit more, but I don't think it will destroy Koji. There's `--enable-repo=local` and there's Fedora i686 config using Koji only already.

**Comment by carlwgeorge** [comment]
I'll be happy to review #1424.

For epel-release we're going to use the `$releasever_major${releasever_minor:+.$releasever_minor}` pattern that was already suggested in that PR.  I think the best approach will be to have two epel10 templates, one without the minor version and one with it, sort of like the separate rawhide/branched templates for Fedora.  CentOS Stream would use epel-10.tpl without the minor version and wouldn't need to be aware of the minor version at all, since the published repo will be `pub/epel/10`.  RHEL would use epel-10-branched.tpl (I'm open to better file names) with the minor version.  This would work best with the RHEL template also integrating the minor versions.  We could use `config_opts['releasever_major'] = '10'` in rhel-10.tpl, and then have files like rhel+epel-10.0-x86_64 that set `config_opts['releasever_minor'] = '0'`.

As an aside, this [visual aid from the EPEL 10 hackfest at Flock](https://carlwgeorge.fedorapeople.org/presentations/epel-10-hackfest-2024-flock.pdf) may be useful for you in understanding which parts of the pipeline will have the minor version and which ones won't.

**Comment by praiskup** [comment]
The `centos-stream+epel-10` chroots for now use `10.0` version, per 3802ca3 (therefore this one was closed).  But there's #1427 where we may use what you suggest.  I'm going to review PRs if you already know which way you prefer.

> then have files like rhel+epel-10.0-x86_64

From the Mock's maintainer perspective, we will need your (EPEL team) help here.  These minor-based configuration files are known from openSUSE world, and it is very hard to catch up.  The set of configuration files will explode, and I'm not very happy about this (the mock-core-configs is used in Fedora Copr, and it would be similar there).

**Comment by carlwgeorge** [comment]
Both the EPEL Steering Committee and the CPE EPEL team are on board with helping wherever we can.  EPEL 10's embracement of minor versions brings many benefits, but we're aware we don't get these for free.  There has already been a tremendous amount of work done towards this goal, with plenty more to do.

I'm not married to the fully minor-based configuration files, but if we do go that route we can include steps in the EPEL branching SOP to send the necessary pull requests to handle the changes.  I'll comment on #1427 with my thoughts around our options on handling this.
