### ISSUE TITLE
RFE: Allow netwotk access in %check only

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/mock#151]
While enabling network access in early build stages would permit all kinds of evils, at %check stage built and installed files should not be modified anymore, so enabling internet access would be ok

Enabling internet access in %check would enable unlocking all the unit tests that rely on cloud services

**Comment by xsuchy** [comment]
> should not be modified anymore

But it can. The use cases are usually:

1) I do not care, how, but just build the damned package (no problems with internet enabled during build)

2) we build for distribution/production and we want to have consecutive builds identical. We do not want to enable inet as that can send data somewhere and sometimes fails sometime not.

If you want to check how the result behave with other services, that is called integration test and there are other services for that: Jenkins, Travis...

I really do not think we should mix that in Mock.

**Comment by nim-nim** [comment]
That may have been true ten years ago but those days there are more and more cloud client tools/libs

Those really need to test connection with the cloud in %check (otherwise the package is useless)

Also, combing unit tests to disable those that access the internet is very time-intensive and error-prone

**Comment by xsuchy** [comment]
If you send a patch I will review it. Otherwise, this will not happen. Sorry.

**Comment by praiskup** [comment]
@nim-nim 
> Those really need to test connection with the cloud in %check

%check can be called even before %install, and as a packager (or
potential attacker) you have turing complete powers in %check.
No, koji must be independent from the outside world.  Not only
for security reasons, but also to ensure that the build does not fail
if the cloud service you test against is down temporarily.

Basically, the service you test against should be opensource, too,
so you can start the service locally during the build-time.  Other
option is to have a look at CI  https://fedoraproject.org/wiki/CI , there
should be internet available because you can not affect the build
results at all.

**Comment by xsuchy** [comment]
To be precise. This will never be a default. The patch I am willing to review have to add this as an opt-in option (config and command line).
