### ISSUE TITLE
gtar and bsdtar mixed options

### ISSUE THREAD

**Issue by fedya** [rpm-software-management/mock#254]
Looks like bsdtar and gtar options is mixing on build
`Executing command: ['bsdtar', '--one-file-system', '-cf', '/var/cache/mock//cooker-riscv64/root_cache/cache.tar', '-C', '/var/lib/mock/cooker-riscv64/root', '--exclude=./proc', '--exclude=./sys', '--exclude=./dev', '--exclude=./tmp/ccache', '--exclude=./var/cache/yum', '--exclude=./var/cache/dnf', '--exclude=^.//proc', '--exclude=^.//sys', '--exclude=^.//dev/shm', '--exclude=^.//dev/pts', '--exclude=^.//var/cache/dnf/', '.'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'en_US.utf8'} and shell False
`
And this issue lead to build fail due to /usr/include/sys not found.

**mock-1.4.14**

Where is issue? 
Here:
https://github.com/rpm-software-management/mock/blob/devel/mock/py/mockbuild/util.py#L971

Why? It's default values for exclude_options regardless what *tar we added to config.

**Comment by berolinux** [comment]
https://github.com/OpenMandrivaAssociation/mock/blob/master/mock-1.4.14-bsdtar-support-for-exclude_dirs.patch

should fix it, but needs more testing than I can do right now

**Comment by fedya** [comment]
@berolinux yes, working fine now.
Need to merge this patch into upstream.

**Comment by schlupov** [comment]
I cannot reproduce your problem on my computer. I set tar in site-defaults.cfg to bsdtar like this:
config_opts['tar'] = "bsdtar" and I got the same result with the patch and without the patch. Executing command looks like this: 
Executing command: ['bsdtar', '--one-file-system', '--use-compress-program', 'pigz', '-cf', '/var/cache/mock/fedora-28-x86_64/root_cache/cache.tar.gz', '-C', '/var/lib/mock/fedora-28-x86_64/root', '--exclude=^./proc', '--exclude=^./sys', '--exclude=^./dev', '--exclude=^./tmp/ccache', '--exclude=^./var/cache/yum', '--exclude=^./var/cache/dnf', '--exclude=^.//proc', '--exclude=^.//sys', '--exclude=^.//dev/shm', '--exclude=^.//dev/pts', '--exclude=^.//var/cache/dnf/', '.'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'en_US.UTF-8'} and shell False

I didn't get the same error, on the other hand, I got more times error: 
pigz: abort: write error on <stdout> (Broken pipe)
bsdtar: Error opening archive: Child process exited with status 32

I'm not sure what is the problem here. Do you also have something set up in config_opts['plugin_conf']['root_cache_opts']['exclude_dirs'] ? Some exclude are in executing command more times, e.g. --exclude=^.//sys' and --exclude=^./sys. Is this a problem?

**Comment by praiskup** [comment]
I tried `$ mock -r fedora-29-x86_64 --shell`, and when it was on "Start: creating root cache", I've seen this command `bsdtar --one-file-system --use-compress-program pigz -cf /var/cache/mock/fedora-29-x86_64/root_cache/cache.tar.gz -C /var/lib/mock/fedora-29-x86_64/root --exclude=./proc --exclude=./sys --exclude=./dev --exclude=./tmp/ccache --exclude=./var/cache/yum --exclude=./var/cache/dnf --exclude=^.//proc --exclude=^.//sys --exclude=^.//dev/shm --exclude=^.//dev/pts .`

So definitely there are some `--exclude` options without anchor, that's because we set the exclude patterns on two places in the code (unification would be nice).

```
pigz: abort: write error on (Broken pipe)
bsdtar: Error opening archive: Child process exited with status 32
```
Seems actually like chroot cache extraction problem (pigz process is unable to write the uncompressed output to pipe which is at the same time read and extracted by bsdtar process).  It doesn't seem to be related to chroot cache creation.
