### ISSUE TITLE
mock not showing all /dev devices with --old-chroot

### ISSUE THREAD

**Issue by khoitd1997** [rpm-software-management/mock#294]
### Short description of the problem
Mock doesn't show all devices in the host's /dev, this causes problems for example when trying to build Fedora remix and the free device reported by ```losetup -f``` doesn't appear in ```/dev```

### Output of `rpm -q mock`
mock-1.4.16-2.fc30.noarch

### Steps to reproduce issue

1. Have more than 5 busy loop device so that losetup -f returns something more than 4
2. Try to do a Fedora build, losetup will then return error

Do not forget to mention full commandline with the mock command you executed.
```shell
mock -r some_file.cfg --old-chroot --cwd=some_dir --chroot a_script
```
### Any additional notes

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

**Comment by xsuchy** [comment]
This is for sure intentional. We do not want to show all devices. Mock provides *minimal* build environment. Previously there were only 4 loop devices, but coincidentally we had recently https://github.com/rpm-software-management/mock/issues/283 - so starting with next release you will be able to specify the number of loop devices.

```
# Default maximum number of dev loops in chroot is 12
# config_opts['dev_loop_count'] = 12
```
