### ISSUE TITLE
Running /usr/sbin/mock as non-root fails with exit 0

### ISSUE THREAD

**Issue by mtinberg** [rpm-software-management/mock#32]
Is it intentional and correct behavior that if /usr/sbin/mock is run by a non-root user in mock.py line 890 it prints out an ERROR message then leaves the exit code as 0 indicating success?  I ran into a bad interaction with other tooling, in this case tito,  which swallowed the error output if the sub-process exited 0 indicating success making it harder to find a $PATH problem that caused this to be run in the wrong way.

**Comment by xsuchy** [comment]
1) since version 1.3.x file /usr/sbin/mock does not exist any more. It has been moved to /usr/libexec/mock/mock which is not in PATH. I altered the error message in commit 517296d
2) I agree that it should return nonzero exit code. It is now returning code 2. Changed in commit 7d7bb6a.

Thank you for reporting.
