### ISSUE TITLE
RFC - rename --old-chroot and --new-chroot

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#331]
This is Request For Comments.

When systemd-nspawn has been added to mock, it brought a lot of bugs. For the transition period we introduced `--old-chroot` and `--new-chroot`. The intent was to steer toward the new chroot as mock running containers is more secure and everything. And maybe one day allow choosing between nspawn, docker, podman and others.

But the world went another way. When people are interested in containers, they usually do not want mock to run a container, but they run mock inside of a container. When mock is running inside of container then there is no need for additional isolation and no one really wants to run another container inside of a container. Therefore the `--old-chroot` is a good choice when you run inside of a container.

My intention is to keep `--old-chroot` indefinitely and actually recommend it when mock is running in a container. And maybe later automatically choose old or new one depending on if mock is running in a container or on bare metal.

In this situation, the names old/new are quite misleading. As it hints that you should rather use the new stuff rather than the old ones.

Therefore I want to rename (in fact, make alias) for those command-line options. 

 * `--old-chroot` -> `--simple-chroot`
 * `--new-chroot` -> `--container-chroot` ??? I want to avoid confusion here whether this option use container for chroot (nspawn) or it is recommended to use when running in container.

I would like to hear your comments and ideas.

**Comment by Conan-Kudo** [comment]
> When mock is running inside of container then there is no need for additional isolation and no one really wants to run another container inside of a container. Therefore the `--old-chroot` is a good choice when you run inside of a container.

I don't think this is actually true. Most people want to be able to do nested containers. The problem is that it doesn't work right now. I'm not sure anyone is working on fixing this issue either. Ideally, nspawn can also function inside an OCI container, as well as the inverse. (cc: @rhatdan, @vrothberg)

> `--new-chroot` -> `--container-chroot`

I'd actually recommend removing this option entirely. We should default to the nspawn backend unless told otherwise.

Alternatively, we could change this to be a selector option type, like so: `--chroot-type=(simple|nspawn)`

The assumption here is that it's possible that more backends could and would get added, like LXC, or QEMU+KVM, etc. This is similar to how `obs-build` handles it, and may make sense for Mock as well.

**Comment by praiskup** [comment]
From maintenance POV, the nspawn support only eats maintenance powers - and brings no additional security, or usefulness (only part of the overall actions is run in container).  Once we can rely on the fact that mock runs just fine in rootless container, **I personally think** we should drop the nested systemd nspawn support entirely.

**Comment by xsuchy** [comment]
> Alternatively, we could change this to be a selector option type, like so: --chroot-type=(simple|nspawn)

:+1: 

> The assumption here is that it's possible that more backends could and would get added, like LXC, or QEMU+KVM, etc. This is similar to how obs-build handles it, and may make sense for Mock as well.

I had this opinion in the past. But nowadays, I do not believe we will have the human power to make this happen in the foreseeable future.

**Comment by Conan-Kudo** [comment]
> I had this opinion in the past. But nowadays, I do not believe we will have the human power to make this happen in the foreseeable future.

Regardless of current manpower, I think switching to a selector actually makes more sense, since you can really only use one of them at a time.

**Comment by praiskup** [comment]
Maybe `--isolation=chroot|nspawn`?

**Comment by cgwalters** [comment]
Bigger picture of course, why have mock/Koji at all really in their current forms versus just having something a bit like Koji schedule a pod in OpenShift that does `yum builddep foo` inside it?  

Anyways yeah, `--isolation=chroot|nspawn` makes sense.

(One complex thing here is that for rpm-ostree, I only really want to support people running it in "sane" environments, which does *not* include what `mock --old-chroot` does.  Today in Fedora infra because the traditional Fedora side uses Koji we do `rpm-ostree compose tree` inside nspawn.  But getting away from that and just using OpenShift as our production build platform is why we are investing in a container-native OS build process in https://github.com/coreos/coreos-assembler )

**Comment by Conan-Kudo** [comment]
> Bigger picture of course, why have mock/Koji at all really in their current forms versus just having something a bit like Koji schedule a pod in OpenShift that does yum builddep foo inside it?

Because that's insane. Aside from the massive complexity burden you are placing on people who are already struggling to deal with package builds at scale, OpenShift isn't even reasonably available in Fedora anymore.

You should strive to make your tooling simple and accessible. So far, I've seen little evidence of that from the new CoreOS tooling.

**Comment by cgwalters** [comment]
> You should strive to make your tooling simple and accessible. 

I am pretty happy with how coreos-assembler is working so far.

BTW, another factor to remember this discussion about mock and the future is that *neither* `--isolation` argument for mock is secure against malicious RPMs, because `yum` is run outside with full privs - and hence neither is Koji secure.  This is a major reason why one really wants to construct the rootfs *inside* the container rather than outside.  (rpm-ostree runs scripts with reasonable isolation though and is somewhat hardened against malicious RPMs, but I'm not making security claims right now, haven't tried to actively break it etc.)

**Comment by Conan-Kudo** [comment]
> BTW, another factor to remember this discussion about mock and the future is that neither `--isolation` argument for mock is secure against malicious RPMs, because `yum` is run outside with full privs - and hence neither is Koji secure.

The new bootstrap mode using an OCI image for bootstrap should resolve that issue.

**Comment by xsuchy** [comment]
> why have mock/Koji at all really in their current forms versus just having something a bit like Koji schedule a pod in OpenShift that does yum builddep foo inside it?

Because then you would end up with a big beast. Something like.... ehm Copr? Mock should be a small tool, which you can easily run locally. And OpenShift orchestration is definitely out of the bound.

It is maybe even time to define the **scope** of Mock. I will create a new RFC issue, where we can discuss it. And this issue should be just about --old-chroot and --new-chroot.

**Comment by wenningerk** [comment]
As mentioned in my remarks on #403 already could we think of having something even 'lighter' than --old-chroot (or whatever it might be called in future)? Could as well imagine an extra option like 'assume-proc-mounted' & 'assume-sys-mounted'.
