### ISSUE TITLE
RFE: add support for .spec in --installdeps

### ISSUE THREAD

**Issue by Frodox** [rpm-software-management/mock#43]
Since both `yum-builddep` and `dnf builddep` supports installing deps for 
```
Install whatever is needed to build the given .src.rpm, .nosrc.rpm or .spec file.
```

I do not see any reasons why mock can't support smth like
```
$ mock -r epel7 --installdeps kernel.spec
INFO: mock.py version 1.3.3 starting (python version = 2.7.5)...
Start: init plugins
INFO: selinux enabled
Finish: init plugins
Start: run
ERROR: Cannot find/open srpm: kernel.spec.  Error: error reading package header
```

```
mock  [options] --installdeps {SRPM|RPM}
```

**Comment by xsuchy** [comment]
Feel free to send patch :)

**Comment by Frodox** [comment]
Ok, I'll try! :) Doesn't look very complex for start

**Comment by plageat** [comment]
I think it is quite complex. There is only one problem to do that: making macro expansion for spec file using macro from buildroot, because of all this conditional BuildReqs in specfile (like %?arch, %?rhel, %?fedora etc.). Solutions:
1) Do it by python rpm:
   1.1 use rpm.spec(). Returns buildrequires, using macro from build system == incorrect result. Also, we can't just use external macro files because there is no such python rpm API (not found by me)
   1.2 so, find all macro files in buildroot, parse/process, substitute system macro by thise from buildroot (can be done with rpm.addMacro()/rpm.delMacro() one by one) = million hours of work and new errors
   1.3 or maybe define/redefine/undefine most common macro manually using info from mock config and undefine = I think the same as above
   1.4 hacking: import rpm in build system, chroot to buildroot, use rpm.reloadConfig() which will set all macro to buildroot's values, go back to build systemm, read specfile with rpm.spec and extract correct buildrequires = tested, does not work
2) Do it with yum-builddep in chroot:
   2.1 copy spec to buildroot, install yumbuildep, install dependencies, (also maybe undo packager transaction of installing yumbuildep or something)

   Any opinions?

**Comment by xsuchy** [comment]
https://github.com/bkircher/python-rpm-spec it will need some improvements, but better than invent something new. And yes the evaluation needs to be done in chroot.

**Comment by plageat** [comment]
> better than invent something new
If so, why don't use the old good yum-builddep?

python-rpm-spec - nice try, but no. I really doubt whether it is useful at all cause it works only as simple spec string parser without any rpm macro expansion (and implementing your own is complex enough)

**Comment by plageat** [comment]
So, what about 2.1?

**Comment by xsuchy** [comment]
Feel free to steel the code from  https://github.com/abrt/abrt/pull/1283

I used rpmspec to eval and parse the spec file, and then just used grep. But alas, still not bullet proof. :(

**Comment by plageat** [comment]
rpmspec tool is ok, but what about el5/el6? As far as I know, rpmspec was introduced somewhere between rpm 4.8 - 4.9
