### ISSUE TITLE
Add command to remove all existing chroots

### ISSUE THREAD

**Issue by jkonecny12** [rpm-software-management/mock#521]
### Short description of the problem
I'm using mock for plenty of things, to test packages, to test builds, test my code behavior on a different system versions. Problem is that when you use mock heavily it's easy to get lost in which chroot still exists and your free space will leak this way.

I know you can look on /var/lib/mock and remove that one by one. However, this is not really inconvenient  when you have hundreds of chroots.

Nice solution have podman and buildah implemented already by ``--all`` option:

https://www.mankier.com/1/podman-rm#--all

### Output of `rpm -q mock`

mock-2.0-2.fc31.noarch

### Steps to reproduce issue

1. mock -r fedora-rawhide-x86_64 --init
2. <future> mock --remove-all-chroots

**Comment by praiskup** [comment]
Thanks for the report.  I'm sure I've seen this somewhere, already.  But
nevermind, let's keep this open for now.  The main obstacle is that we
don't have (yet?) any database we could use for tracking what chroots are
initialized (note the -r, --unique and --rootdir options).

**Comment by jkonecny12** [comment]
Wouldn't it be better to look on created chroots in /var/lib than create a database? Making this dynamic could make your code less complicated thought.

**Comment by nkadel** [comment]
It seems dangerous: There is no graceful "locking" of other build processes, which may be using those chroot cages, do avoid deleting one in the midst of the build. Hilarity could ensue if someone else or an automated process is running a build. Since I have builds that can take an hour, the risk can be real.

**Comment by jkonecny12** [comment]
@nkadel in your case you can avoid calling this. I don't expect to have an automatic removal of all chroots. You have to call it explicitly.

**Comment by nkadel** [comment]
I want it as a cleanup step for failed builds, especially if one of the chroots has some testing packages in it.

The problem is exacerbated by the recently updated names of epel based cfg files in mock-core-configs-36.4. "epel-8-x86_64" evaporated, and there is no new .cfg file with the matching /var/lib/mock/epel-8-x86_64, or /var/cache/mock/epel-8-x86_64. That tripped me upsetting up local .cfg files based on the new centos+epel-8-x86_64 and taking up a bunch of system resources with the old cache.

It's not a casual problem to avoid accidental conflicts with running or freshly started mock builds, especially with no robust existing lock mechanism, and it's complicated by the possibility of using .cfg files that are local rather than in /etc/mock/ for tracking. It's theoretically possible to run a script to run "mock -r /etc/mock/{config}.cfg --scrub=all" for every config, as a start, and to then scrub the caches individually. But the chroot cage, especially /var/lib/mock/{config}/, may have mountpoints under it which should be unmounted before clearing those cages, and the cleanup skipped if those are still present. It's a pretty little problem.
