### ISSUE TITLE
set user_agent in dnf.conf

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#562]
Mock should set 'user_agent' in dnf.conf to identify as a build system.

See https://bugzilla.redhat.com/show_bug.cgi?id=1813424

**Comment by dmnks** [comment]
It turns out the default `/usr/lib/os-release` file that's shipped with the `fedora-release` package does not contain the `VARIANT_ID` key at all. It's only set in the respective `fedora-release-<variant>` subpackages, but mock does not install any of those in its containers.

That means, I think the best solution here would be to actually do the following:
1. Replace the `/etc/os-release` symlink with the file `/usr/lib/os-release`
2. Add `VARIANT_ID=mock` to `/etc/os-release`.

The resulting `User-Agent` string would then look like this (for example):
`libdnf (Fedora 31; mock; Linux.x86_64)`
