### ISSUE TITLE
RFE: Parameterized config files

### ISSUE THREAD

**Issue by opoplawski** [rpm-software-management/mock#6]
I'm facing a situation where I'm having an explosion of multiple config files what only differ slightly, and the difference could expressed by passing an argument to mock.  Does something like that seem feasible?

It would look something like:

```
mock -r epel-7-x86_64-nwra-intel --param intel_version=2016.4.258 ....
```

With the config file having:

```
config_opts['chroot_setup_cmd'] = 'install @buildsys-build altcc-rpm-macros rpm-opt-hooks nwra-compiler-%{intel_version}'
config_opts['files']['/etc/profile.d/zz-nwra.sh'] = """
export MODULEPATH=/opt/modulefiles/Core:$MODULEPATH
module load intel/%{intel_version}
"""
```

This could even be applied to current configs that differ only by version number.

**Comment by xsuchy** [comment]
Sounds good. Maybe just the syntax of that variable (%{intel_version}). It is the same as name of macro. So it may be already used somewhere in config and can conflict. And we already use %(foo) as replacement string on several places.

And the problem is that there is no code, which do the replacement for all variables. So current replacement is done only for some variables and just before they are used. 
E.g %(cache_topdir)s is only replaced in config_opts['plugin_conf']['yum_cache_opts']['dir'] but not in other variables.

**Comment by Frodox** [comment]
Did you tried to use [`include` feature](https://github.com/rpm-software-management/mock/blob/devel/etc/mock/site-defaults.cfg#L15) ?

**Comment by Frodox** [comment]
@xsuchy I generally also lobe this idea and need this feature. Do you have any thoughts / vision of 'how it should be', so I can try to implement it

**Comment by xsuchy** [comment]
@Frodox First we need to handle https://bugzilla.redhat.com/show_bug.cgi?id=1208344#c3 I.e. have some template mechanism which is capable of substituting variables in *all* config variables. When this is done, then we can do another step and declare those variables on command line.

**Comment by Frodox** [comment]
@xsuchy hmm, I have another idea :) Because it is usage-related.. We need not to create combine/universal monster for every substitution to implement this feature/usecase I think.

IMHO, First step is
* create scratch of `config_opts` before reading any configs (looks like it is implemented already)
* fill it with cmdline args **before** reading configs (I think it isn't hard to implement, because it is already done for site-config -> myconfig -> included configs chain)

And even in this case, it would be possible to fill macroses from command line and use it as parameters :D
```bash
# myconfig.cfg
if "%with_debug_repo" in config_opts['macros']:
    print("enabling debug repo")
    include("extra-config-with-extra-repo.cfg")
```
and so on.

But final idea (second step) - How about creating extra dict for such user-parameters ?
Like 
```bash
mock --param "key value" --param "key2 value2" -r config ...

# config.cfg
if "key" in config_opts['user-opts']:
   do some special stuff (like include)
```

and so on. If the main idea is to use some params inside config to change a logic slightly, I think it is a good idea and isn't hard to implement.

**Comment by xsuchy** [comment]
Several issues with your blueprint:

* you cannot replace the variables at  the beggining, because e.g. config_opts['plugin_conf']['ccache_opts']['dir'] = "%(cache_topdir)s/%(root)s/ccache/u%(chrootuid)s/" needs to be filled in only when you know the correct value, which is somewhere in the middle of code. So you should expand it just before using it.

* in your proposal you will have to create list of variables which are user defined, this is PITA. it is much easier to replace everyone if they appear there.

* and I did not even mentioned recursion: 
    config_opts['opts1'] = '%(opts2)'
   config_opts['opts2'] = '%(opts3)'
    config_opts['opts3'] = 'foo bar'
  where you will have to work on correct ordering.

And rather then inventing wheel, it better to take some existing library. E.g. jinja2 and use that.

**Comment by Frodox** [comment]
@opoplawski as workaround for slight changes I thought we can use just env variables :) 
Since config file - just python, there is no problem with it (plus read [FAQ](https://github.com/rpm-software-management/mock/wiki/FAQ#how-to-preserve-environment-variable-in-chroot))

another way - write some plugin for it or use `m4`. Because I'm also need to have slight changes for some packages (like, build it only on one core, or add extra repo for some packages, or clean cache for some packages and so on)

**Comment by plageat** [comment]
Another question is how would you differ/write options from multiple config levels. Right now, every substitution like '%(name)' is a direct config's dict key (like %(cache_topdir), %(root), %(chrootuid) etc.) Consider imaginary example:

3 roots defined for different levels:

config['root'] = '/some/root/path'] # level 0
config['whatever_nested_conf']['root'] = '/some/root/path/lvl1' # level 1
config_opts['plugin_conf']['yum_cache_opts']['root'] =  '/some/root/path/lvl2' # level 2

Now I want use %(root) (assuming format is '%()' or whatever):

config_opts['my_path'] = '%(root)/some/path' #  taken form level 0 by default ?

but if I want root from level 2, it may look like:
config_opts['my_path'] = '%(plugin_conf:yum_cache_opts:root)/some/path' # emm...really?
or:
config_opts['plugin_conf']['yum_cache_opts']['somepath'] = \
'%(plugin_conf:yum_cache_opts:root)/another/path' # well..

**Comment by praiskup** [comment]
Seeing original OP's motivation, include seems to be the answer (and it was also 
original motivation for filling RFE and implementing it.  If you care about templating,
and we are talking about python project, consider jinja2 please if any (e.g.
https://github.com/devexp-db/distgen).

**Comment by xsuchy** [comment]
Going through old issues. Since last release Mock support Jinja2 templates https://github.com/rpm-software-management/mock/wiki/Release-Notes-1.4.14#mock-new-features
You can define any parameter using `--config-opts=KEY=VALUE` and you can use it anywhere using `{{ KEY }}` I guess we can close this.
