### ISSUE TITLE
epelplayground chroots don't build

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#620]
```
epel-release epel-rpm-macros fedpkg-minimal --setopt=tsflags=nocontexts
DEBUG: Unsharing. Flags: 134217728
No matches found for the following disable plugin patterns: local, spacewalk
CentOS-8 - Base                                  12 MB/s | 2.2 MB     00:00
CentOS-8 - AppStream                             21 MB/s | 5.8 MB     00:00
CentOS-8 - PowerTools                            11 MB/s | 1.9 MB     00:00
CentOS-8 - Extras                                33 kB/s | 7.3 kB     00:00
Extra Packages for Enterprise Linux 8 - Playgro  15 MB/s | 6.1 MB     00:00
Error:
 Problem: conflicting requests
  - nothing provides fpc-srpm-macros needed by epel-rpm-macros-8-16.playground.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Semi-question asked here:
https://bugzilla.redhat.com/show_bug.cgi?id=1875057

**Comment by praiskup** [comment]
epel-devel report:
https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/LFAQVUH6RLZXCLWHN5PR7ZR2LZAOQSQV/

**Comment by tdawson** [comment]
EPEL Playground is in the middle of changing.
It will no longer be a "stand alone" repository.  It will be for only those packages that people are using to "play with" large changes to their packages.  There will be no more automatic builds of all
packages.

Because of this, you will need to have the regular EPEL repository enabled in order to use the EPEL-Playground repository.

We're right in the middle of this change, but fixing mock now is the best time to do it.  It won't hurt anything to add the regular EPEL repository now, when doing the EPEL-Playground mock.

**Comment by praiskup** [comment]
> We're right in the middle of this change, but fixing mock now is the best time to do it. 

Ok, PR #634 makes playground config to transitively depend on epel-8, can you take a look?
