### ISSUE TITLE
Mount options for recursive bind-mounts (rbind) are not used recursively

### ISSUE THREAD

**Issue by dpward** [rpm-software-management/mock#713]
When systemd-nspawn is not used, mock will mount /proc and /sys in the chroot by making a recursive bind-mount (`rbind`) from those paths in the host filesystem. In addition to using the `rprivate` option to disable propagation, [the code specifies](https://github.com/rpm-software-management/mock/blob/96adbbb6ebdb7e7ebf5aa7f3813573acfd27a6f5/mock/py/mockbuild/mounts.py#L186) the mount options `nodev,noexec,nosuid,readonly` should be set.

However, these mount options are only applied to the /proc and /sys mounts themselves in the chroot; they do not affect any submounts such as /sys/kernel/debug. This is consistent with the [mount(8)](https://man7.org/linux/man-pages/man8/mount.8.html) man page, which says:
> It's impossible to change mount options recursively (for example with **-o rbind,ro**).

It seems that to achieve this, mock might have to identify all of the submounts somehow, and change the mount options for each one individually.

**Comment by praiskup** [comment]
This originates from 02c4d19c2b7097e5d1312fe5d27315b080237e41.  The whole
motivation there was to **make everything work** inside rootless container
:-) - rather than attempting to harden the build.  The patch broke mock
from several aspects, so there are several follow-up patches.

I don't think we necessarily have to make an action here - as we don't
pretend that we completely isolate the build environment (users who really
care should at least use --isolation=nspawn) or run mock in rootless
podman container.

I'm closing because there's low motivation to touch this code, but if you
plan to fix this, patches are welcome (but this requires careful patches,
and I doubt it would be trivial contribution).
