### ISSUE TITLE
Bind mount for files (not just directories)

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#87]
See https://github.com/rpm-software-management/mock/commit/73deb9d61f824210065b37ffd4838e5f9a533574#commitcomment-22758334

**Comment by ifireball** [comment]
bind-mounting socket files into chroots and containers seems to be common practice, see for example:

Recommendation for mounting the socket instead of trying to run Docker in Docker:
https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

It seems to be a common thing to do this to the libvirt socket as well.

**Comment by xsuchy** [comment]
This has been implemented in 72a558e
