### ISSUE TITLE
eurolinux signature problems on subset of packages cause build failures

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#974]
```
GPG key at file:///usr/share/distribution-gpg-keys/eurolinux/RPM-GPG-KEY-eurolinux9 (0x1C9FD080) is already installed
The GPG keys listed for the "EuroLinux 9 AppStream All" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: perl-PathTools-3.78-461.el9.i686
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/eurolinux/RPM-GPG-KEY-eurolinux9
Public key for perl-Socket-2.031-4.el9.i686.rpm is not installed. Failing package is: perl-Socket-4:2.031-4.el9.i686
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/eurolinux/RPM-GPG-KEY-eurolinux9
Public key for perl-Storable-3.21-460.el9.i686.rpm is not installed. Failing package is: perl-Storable-1:3.21-460.el9.i686
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/eurolinux/RPM-GPG-KEY-eurolinux9
Error: GPG check FAILED
```

**Comment by praiskup** [comment]
@istiak101 @AlexBaranowski can you take a look please?

**Comment by AlexBaranowski** [comment]
Hey, I will look into it ATM.

**Comment by AlexBaranowski** [comment]
I would like to confirm that this is reproducible. I did:

- [x] Check that mock key is the proper one.
- [x] Reproduced the issue by building the package - perl-Storable-3.21-460.el9.src.rpm
- [x] Check remotes repos and our repo - it's the same file

Then I did the following to apply the fixes so that it won't happen in the future:

- [x] Check the QA status -> then tests -> then configs where I found that buildroots repos are not tested for signature.
- [x] I also checked why our internal build system (Gaia) and why it didn't complain about this issue before and fixed that
- [x] Implemented/add tests that are running at the moment - it will take some time as repoquery does not support the signature tags so tests have to iterate over the filesystem

After running the tests, that OFC will fail, I will schedule the rpms to be resigned and then pushed to repos. I will write here that it's fixed.

@praiskup Thank You very much for Your report and help.

**Comment by AlexBaranowski** [comment]
It should be fixed. I rebuild perl-Storable-3.21-460.el9.src.rpm without issue.

Once more thank You for the report.

Best,
Alex

**Comment by praiskup** [comment]
Thank you for the quick fix!

**Comment by praiskup** [comment]
JFTR, looks fine:
```
PASSED: eurolinux-8-i686.cfg (tmpfs)
PASSED: eurolinux-8-i686.cfg
PASSED: eurolinux-8-x86_64.cfg (tmpfs)
PASSED: eurolinux-8-x86_64.cfg
PASSED: eurolinux-9-i686.cfg (tmpfs)
PASSED: eurolinux-9-i686.cfg
PASSED: eurolinux-9-x86_64.cfg (tmpfs)
PASSED: eurolinux-9-x86_64.cfg
```
